# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8EnzM0vLy4kxU9m0LODsS3jPVtytt_i
"""

pip install pandas numpy spacy scikit-learn fastapi uvicorn joblib matplotlib seaborn nltk

import pandas as pd
path = "/content/drive/MyDrive/Dataset/DataSet.csv"
df = pd.read_csv(path)
print(df)